### ISSUE TITLE
(RNF-03) Criação de uma Logo (Alta)

### ISSUE THREAD

**Issue by TomazMPP** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e1-proj-web-t14-ProjDevTask#4]

**Comment by ghost** [comment]
![DEVTASK](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e1-proj-web-t14-ProjDevTask/assets/62924010/63114ef3-331d-4144-9abd-5e537210fb6a)
![DEVTASK icon](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e1-proj-web-t14-ProjDevTask/assets/62924010/f3f2f881-c1e9-4c9d-b009-a67c14f66266)
